<a href="https://colab.research.google.com/github/Mgobeaalcoba/Deepnote_Repository/blob/main/Producto_interno_entre_dos_matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
B = np.array([[2,3],[5,7],[11,13]])

In [5]:
print(A)
print("\n")
print(A.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)


In [6]:
print(B)
print("\n")
print(B.shape)

[[ 2  3]
 [ 5  7]
 [11 13]]


(3, 2)


In [8]:
C = A.dot(B)
print(C)

[[ 45  56]
 [ 99 125]
 [153 194]
 [207 263]]


In [11]:
# D = B.dot(A) # ValueError: shapes (3,2) and (4,3) not aligned: 2 (dim 1) != 4 (dim 0)
# Para poder hacer el producto de dos matrices debe estar alineado la cantidad de columnas de la primera matriz y la cantidad de filas de la segunda matriz
# la resultante será una matriz de tantas filas como la primera matriz y de tantas columnas como la segunda
# el orden de multiplicado es: 1 fila de matriz uno por 1 columna de matriz 2 da como resultado el escalar [0][0] de mi 
# nueva matriz. 1 fila de matriz 1 por 2 columna de matriz 2 da como resultado el escalar [0][1] de la nueva 
# matriz. 2 fila de matriz uno por columna 1 de matriz dos da como resultado el escalar [1][0] de la nueva matriz
